### ISSUE TITLE
ReVanced Builder Issues with v3.9.2

### ISSUE THREAD

**Issue by Ryuytyuu-Greseven** [reisxd/revanced-builder-py#2]
Yeah, 
I know this is not Appropriate to mention #revanced-builder issues here. But that repo is archived. Can't update anything there. 

Well Revanced Builder is popular one and a lot of people are still using it.
So would you please remove it from archive, so that issue fixing PR can be raised.

Regards
A User of Revanced Builder.

**Comment by Sinneida** [comment]
Yeah, that's very odd that author decided to archive the repo out of the blue. If the project has to be buried due to some reasons (even if they're legal ones) some short statement would be nice.

**Comment by Legitti** [comment]
yeah, thats a shame. poor communication.
